### ISSUE TITLE
Missing audio.mp3

### ISSUE THREAD

**Issue by Ch1sKey** [fword-dev/f-word.dev#2]
`npm start` Thrown an Error `TemplateContentRenderError` with Eleventy templates with cause:

`Error: ENOENT: no such file or directory, stat 'src/episodes/1/audio.mp3'`

**Comment by pepelsbey** [comment]
Yes, it doesn’t have the audio files in the repository. I should probably enable the dev/production mode or use LFS to store files in git.

I’ll think about the possible solution that would help community to contribute. Thank you for heads up!

**Comment by pepelsbey** [comment]
MP3 files are now tracked in the repository via Git LFS, so you should be able to clone and build it locally.
